name = "fortest-assertions"
version = "0.1.0"
license = "MIT"
author = "Kohei Yokota"
maintainer = "yokotakohei"
copyright = "Copyright 2026 Kohei Yokota"
description = "Fortran assertion module for fortest testing framework"
categories = ["testing"]
keywords = ["testing", "assertions", "fortran", "unit-testing"]

[build]
auto-executables = false
auto-tests = false
auto-examples = false

[library]
source-dir = "src"

[install]
library = true